src/Entity/Conversation.php
<?php

namespace App\Entity;

use App\Repository\ConversationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ConversationRepository::class)]
class Conversation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'conversations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user1 = null;

    #[ORM\ManyToOne(inversedBy: 'conversations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user2 = null;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'conversation')]
    private Collection $messages;

    #[ORM\ManyToOne(inversedBy: 'conversations')]
    private ?TradeRequest $Trade = null;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser1(): ?User
    {
        return $this->user1;
    }

    public function setUser1(?User $user1): static
    {
        $this->user1 = $user1;

        return $this;
    }

    public function getUser2(): ?User
    {
        return $this->user2;
    }

    public function setUser2(?User $user2): static
    {
        $this->user2 = $user2;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setConversation($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getConversation() === $this) {
                $message->setConversation(null);
            }
        }

        return $this;
    }

    public function getTrade(): ?TradeRequest
    {
        return $this->Trade;
    }

    public function setTrade(?TradeRequest $Trade): static
    {
        $this->Trade = $Trade;

        return $this;
    }





}

src/Controller/ConversationController.php
<?php

namespace App\Controller;

use App\Entity\Conversation;
use App\Entity\Message;
use App\Entity\TradeRequest;
use App\Entity\User;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Validator\Constraints\Timezone;

#[IsGranted('ROLE_USER')]
class ConversationController extends AbstractController
{
    #[Route('/conversation', name: 'app_conversation')]
    public function index(EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {
        $user = $this->getUser();
        $conversations = $userRepository->getConversationsByUser($user);

        return $this->render('conversation/index.html.twig', [
            'user' => $user,
            'conversations' => $conversations,
        ]);
    }
    #[Route('/nouvelle-conversation/{id}', name: 'app_conversation_new')]
    public function newConversation(TradeRequest $tradeRequest,EntityManagerInterface $entityManager, UserRepository $userRepository, Request $request): Response
    {
        $user = $this->getUser();
        $conversations = $userRepository->getConversationsByUser($user);

        if ($request->isMethod('POST')) {
            // Récupérer les données du formulaire soumis
            $authorId = $request->request->get('author');
            $userId = $request->request->get('user');

            // Récupérer les utilisateurs par leur ID
            $author = $userRepository->find($authorId);
            $user = $userRepository->find($userId);

            // Créer une nouvelle conversation
            $conversation = new Conversation();
            $conversation->setUser1($author);
            $conversation->setUser2($user);
            $conversation->setTrade($tradeRequest);

            // Enregistrer la conversation dans la base de données
            $entityManager->persist($conversation);
            $entityManager->flush();

            $this->addFlash('success','Conversation créée avec succès');
            return $this->redirectToRoute('app_conversation');
        }

        return $this->render('conversation/messages.html.twig', [
            'user' => $user,
            'conversations' => $conversations,
        ]);
    }
    #[Route('/conversation/{id}/messages', name: 'app_conversation_messages')]
    public function showMessages(Conversation $conversation, EntityManagerInterface $entityManager, Request $request): Response
    {
        if ($request->isMethod('POST')) {
            $content = $request->request->get('content');

            // Récupération de l'ID du destinataire à partir de la relation de commerce de la conversation
//            $receiverId = ;
            // Création d'une nouvelle instance de Message
            $message = new Message();
            $message->setConversation($conversation);
            $message->setEmitter($entityManager->getRepository(User::class)->find($this->getUser()));
            $message->setReceiver($conversation->getTrade()->getAuthor());

            $message->setContent($content);
            $message->setDatetime(new \DateTime('now', new \DateTimeZone('Indian/Reunion'))); // Assurez-vous de définir la date et l'heure correctement

            // Persistez le message dans la base de données
            $entityManager->persist($message);
            $entityManager->flush();
        }

        // Récupération de tous les messages de la conversation
        $messages = $conversation->getMessages();
        // Rendu de la vue Twig avec les messages et la conversation
        return $this->render('conversation/messages.html.twig', [
            'messages' => $messages,
            'conversation' => $conversation,
        ]);
    }
}

templates/conversation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Boite de réception{% endblock %}

{% block body %}
    <div>
        <section class="bg-white py-2 antialiased  md:py-5">
            <div class="mx-auto max-w-screen-xl md:px-4 px-1 2xl:px-0">
                <h2 class="text-3xl text-center font-semibold text-gray-900 mt-3">Conversations</h2>
                <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-5 dark:bg-gray-700">
                <div class="mt-2 divide-y divide-gray-200 flex flex-wrap w-full">
                    {% for conversation in conversations %}
                        <div class="md:max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow m-2 w-full">
                            <a href="#">
                                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 ">{{ conversation.user1.lastName }} {{ conversation.user1.firstName }} &
                                    {{ conversation.user2.lastName }} {{ conversation.user2.firstName }}</h5>
                            </a>
                            <p class="text-sm font-normal text-gray-500 ">Messages : ({{ conversation.messages|length }})</p>
                            <p class="mb-3 font-normal text-gray-700 ">Pouvoir de l'annonce : {{ conversation.trade.power.name }}</p>
                            <a href="{{ path('app_conversation_messages', {'id': conversation.id}) }}" class="inline-flex items-center px-5 py-2.5 text-sm font-medium text-center bg-primary-100 text-primary-800 border-primary-500 rounded-lg focus:ring-4 focus:ring-primary-200">
                                Voir les messages
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>

    </div>

{% endblock %}

templates/conversation/messages.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conversation{% endblock %}

{% block body %}

    <div class="h-[calc(100vh-6rem)] flex flex-col mt-5">
        <h2 class="text-3xl text-center font-semibold text-gray-900 mt-3">Messages (Pouvoir : {{ conversation.trade.power.name }}) </h2>
        <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-5 dark:bg-gray-700">
        <div class=" flex-1 overflow-y-scroll">
            <div class="px-4 py-2">
                {% set currentUser = app.user %}
                {% for message in messages %}
                    {% if message.emitter == currentUser %}
                        {# Afficher le message de l'utilisateur connecté #}
                        <div class="flex items-center justify-end mb-2">
                            <div class="bg-primary-600 text-white rounded-lg p-2 shadow mr-2 max-w-sm">
                                {{ message.content }}
                            </div>
                            <img class="w-8 h-8 rounded-full" src="{{ app.user.profilePicture }}" alt="User Avatar">
                        </div>
                    {% else %}
                        {# Afficher le message de l'autre utilisateur #}
                        <div class="flex items-center mb-2">
                            <img class="w-8 h-8 rounded-full mr-2" src="{{ message.emitter.profilePicture }}" alt="User Avatar">
                            <div class="font-medium">{{ message.emitter.lastname }} - {{ message.emitter.firstname }}</div>
                        </div>
                        <div class="bg-white rounded-lg p-2 shadow mb-2 max-w-sm">
                            {{ message.content }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>

        <div class=" px-4 py-2">
            <form action="" method="post">
                <div class="flex items-center">
                    <input name="content" class="w-full border rounded-full py-2 px-4 mr-2" type="text" placeholder="Saisissez votre message...">
                    <input type="hidden" value="{{ conversation.id }}" name="conversationId" >
                    <input type="hidden" value="{{ app.user.id }}" name="emitter_id" >
                    {#                <input type="text" value="{{ conversation.trade.author }}" name="receiver_id" >#}
                    <button type="submit" class="bg-primary-600 hover:bg-primary-700 text-white font-medium py-2 px-4 rounded-full">
                        Envoyer
                    </button>
                </div>
            </form>

        </div>
    </div>

{% endblock %}